In [45]:
filename = 'puzzle_five.txt'
with open(filename) as f:
    data = f.readlines()
    for counter in range(len(data)): 
        data[counter] = data[counter].rstrip('\n')

In [36]:
row_numbers = []
col_numbers = []
seat_ids = []

for seat_ast in data:
    row_ast = seat_ast[:-3]
    col_ast = seat_ast[-3:]
    
    rows = [i for i in range(0,128)]
    cols = [i for i in range(0,8)]
    
    for char in row_ast:
        length = len(rows)
        pop_amount = int(length/2)
        counter = 0
        if char == 'B':
            while counter < pop_amount:
                throw_away = rows.pop(0)
                counter += 1
        if char == 'F':
            while counter < pop_amount:
                throw_away = rows.pop()
                counter += 1
    for x in rows:
        row_numbers.append(x)
    
    for char in col_ast:
        length = len(cols)
        pop_amount = int(length/2)
        counter = 0
        if char == 'L':
            while counter < pop_amount:
                throw_away = cols.pop()
                counter += 1
        if char == 'R':
            while counter < pop_amount:
                throw_away = cols.pop(0)
                counter += 1
    for x in cols:
        col_numbers.append(x)
        
for counter in range(len(row_numbers)):
    seat_id = (row_numbers[counter] * 8) + col_numbers[counter]
    seat_ids.append(seat_id)

[818, 572, 193, 334, 497, 714, 726, 664, 652, 80, 699, 725, 120, 577, 856, 575, 405, 543, 136, 782, 522, 891, 429, 654, 795, 871, 217, 648, 635, 490, 855, 555, 798, 189, 573, 492, 753, 607, 666, 109, 240, 689, 885, 636, 138, 308, 705, 354, 115, 867, 721, 599, 709, 603, 376, 322, 188, 187, 592, 415, 339, 446, 637, 79, 535, 420, 212, 829, 204, 485, 401, 597, 892, 665, 132, 643, 808, 828, 882, 306, 351, 209, 286, 814, 357, 153, 683, 811, 427, 294, 317, 311, 737, 803, 647, 590, 817, 658, 95, 739, 509, 384, 54, 680, 234, 259, 582, 616, 350, 397, 246, 631, 623, 550, 399, 218, 121, 734, 669, 800, 707, 801, 530, 146, 93, 365, 624, 222, 112, 629, 697, 677, 390, 512, 815, 545, 802, 129, 156, 53, 760, 521, 511, 78, 715, 732, 393, 576, 820, 894, 96, 567, 673, 701, 480, 340, 119, 162, 268, 772, 711, 126, 768, 875, 58, 834, 296, 528, 770, 712, 784, 735, 696, 378, 167, 371, 312, 538, 336, 239, 70, 288, 267, 500, 413, 743, 661, 125, 342, 687, 105, 163, 487, 861, 791, 478, 458, 262, 821, 231, 325, 717, 593, 627, 107, 102, 887, 431, 92, 433, 546, 713, 524, 869, 316, 148, 145, 684, 601, 260, 235, 276, 210, 839, 280, 525, 764, 568, 412, 639, 876, 435, 728, 225, 692, 114, 691, 302, 149, 825, 755, 398, 324, 236, 527, 819, 849, 274, 804, 459, 559, 89, 314, 580, 613, 738, 620, 343, 382, 326, 615, 377, 481, 583, 761, 618, 402, 822, 519, 440, 863, 469, 67, 359, 151, 223, 438, 775, 625, 219, 368, 273, 835, 128, 533, 574, 117, 237, 348, 877, 837, 186, 275, 779, 97, 214, 771, 255, 177, 68, 499, 443, 498, 108, 94, 66, 759, 434, 626, 896, 838, 437, 341, 140, 578, 532, 862, 716, 602, 462, 796, 62, 731, 57, 72, 408, 515, 455, 552, 366, 290, 746, 600, 859, 566, 451, 504, 812, 448, 200, 409, 491, 55, 723, 751, 410, 857, 139, 56, 447, 338, 161, 688, 88, 207, 749, 323, 611, 404, 190, 668, 733, 507, 106, 449, 693, 301, 450, 282, 220, 845, 352, 832, 797, 853, 793, 851, 702, 134, 347, 238, 783, 586, 387, 879, 369, 135, 881, 727, 321, 176, 640, 517, 806, 313, 175, 830, 762, 883, 344, 617, 672, 295, 595, 633, 452, 211, 328, 385, 483, 425, 510, 844, 335, 579, 570, 318, 414, 113, 59, 310, 319, 461, 657, 718, 475, 565, 164, 548, 816, 104, 482, 464, 785, 710, 263, 872, 496, 826, 630, 127, 729, 349, 670, 356, 780, 184, 424, 539, 529, 394, 353, 660, 895, 840, 201, 585, 744, 610, 790, 556, 807, 254, 173, 704, 736, 558, 284, 300, 226, 411, 742, 752, 747, 645, 154, 745, 307, 100, 531, 157, 788, 468, 777, 133, 591, 874, 389, 192, 170, 242, 553, 674, 884, 396, 662, 292, 823, 756, 436, 619, 587, 562, 477, 123, 789, 634, 841, 407, 305, 846, 159, 864, 87, 257, 83, 518, 465, 110, 213, 466, 758, 131, 852, 850, 391, 233, 143, 581, 147, 111, 534, 547, 179, 730, 720, 224, 64, 285, 372, 494, 63, 836, 418, 332, 454, 171, 653, 256, 604, 191, 168, 503, 180, 542, 750, 261, 98, 65, 439, 792, 523, 265, 776, 216, 309, 763, 330, 289, 778, 893, 767, 383, 457, 799, 476, 470, 416, 194, 596, 873, 85, 886, 208, 76, 554, 281, 526, 250, 569, 724, 843, 473, 675, 374, 741, 486, 813, 781, 488, 278, 474, 868, 453, 258, 196, 655, 833, 787, 346, 406, 241, 557, 501, 381, 584, 605, 199, 230, 183, 878, 536, 537, 748, 769, 271, 69, 644, 706, 84, 520, 228, 642, 185, 663, 456, 195, 227, 827, 142, 297, 608, 722, 563, 81, 831, 708, 165, 794, 638, 740, 103, 130, 245, 364, 460, 244, 544, 493, 824, 489, 422, 467, 860, 331, 502, 158, 375, 685, 612, 765, 628, 144, 805, 249, 614, 426, 86, 197, 430, 386, 232, 155, 160, 345, 809, 858, 71, 516, 561, 671, 253, 506, 360, 299, 269, 754, 471, 337, 283, 589, 560, 564, 651, 174, 463, 221, 75, 646, 279, 428, 848, 205, 178, 588, 247, 703, 786, 277, 847, 370, 266, 91, 124, 172, 363, 540, 380, 206, 203, 432, 598, 122, 392, 169, 757, 549, 444, 181, 137, 99, 333, 541, 61, 649, 118, 403, 681, 74, 442, 73, 650, 82, 362, 367, 682, 698, 594, 101, 889, 166, 773, 141, 423, 202, 248, 766, 774, 870, 182, 215, 243, 329, 888, 287, 690, 842, 251, 632, 866, 252, 150, 514, 291, 609, 304, 890, 373, 513, 400, 484, 495, 641, 700, 445, 667, 479, 417, 622, 695, 361, 298, 270, 327, 551, 441, 60, 656, 419, 508, 229, 198, 865, 388, 686, 272, 152, 621, 90, 719, 303, 694, 472, 854, 606, 880, 77, 571, 264, 116, 355, 320, 676, 358, 505, 679, 315, 293, 379, 810, 421, 395, 678]
896

In [40]:
seat_ids.sort()
print(seat_ids)

[53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896]

In [44]:
differences = []
for counter in range(len(seat_ids)):
    if counter < len(seat_ids) - 1:
        difference = seat_ids[counter + 1] - seat_ids[counter]
        if difference == 2:
            print(counter)
        differences.append(difference)
        
print(seat_ids[605])

605
658